name: Build
on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout the code
                uses: actions/checkout@v3

            -   name: Setup JDK 17
                uses: actions/setup-java@v3
                with:
                    distribution: 'corretto'
                    java-version: 17
                    cache: 'gradle'

            -   name: Generate debug build
                run: ./gradlew assembleDebug

            -   name: Upload APK
                uses: actions/upload-artifact@v3
                with:
                    name: app_debug
                    path: app/build/outputs/apk/debug/app-debug.apk
